### PR TITLE
resolves issue#3 and issue#4

### PR DESCRIPTION
**Pull request by 0xMarvell**
Added views for register and login.
Connected the views to the templates.
Users can now login with either username or email.

### CODE REVIEW

**Comment by 0xMarvell** [comment]
Since we're using poetry to manage dependencies, 
I added all the packages to the poetry file.. now instead of `pip install -r requirements.txt` 
install all the dependencies like so - `poetry install`.
to install any new packages, make sure you're in the same directory with the poetry.lock file and run `poetry add <package-name>`
I also added a gitignore file so we don't push any clutter files..including the sqlite3 file...please delete it from the online repo thanks. @CaptainVee

**Comment by CaptainVee** [comment]
Nice work. i really didn't consider all these. Please write all the stuffs on the readme so others can see it

**Review by CaptainVee — COMMENTED** [review]
you shouldn't have edited the welcome function in the workspace views, it checkes to log the user to his current workspace.

**Comment by CaptainVee** [comment]
Also add the hactober label when next you're making a PR

**Pull request merged**
